-- Murach's SQL Sever 2016 for developers
-- SQL Using Murch's My Guitar Shop

DECLARE @ProductName VARCHAR(50), @ListPrice NUMERIC(10,2)

DECLARE PRODUCTS_CUR CURSOR 
FOR 
	SELECT ProductName, ListPrice 
	FROM PRODUCTS 
	WHERE ListPrice > 700
	ORDER BY ListPrice DESC;
OPEN PRODUCTS_CUR

IF @@CURSOR_ROWS > 0
	BEGIN 
	FETCH NEXT FROM PRODUCTS_CUR INTO @ProductName, @ListPrice
	WHILE @@Fetch_status = 0
		 BEGIN
			PRINT @ProductName +', $'+CONVERT(VARCHAR,@ListPrice)
			FETCH NEXT FROM PRODUCTS_CUR INTO @ProductName, @ListPrice
		END
	END

CLOSE PRODUCTS_CUR
DEALLOCATE PRODUCTS_CUR
